- name: Collect customer information
  hosts: localhost

  tasks:
    - name: Fetch Helm repo data from URL
      ansible.builtin.uri:
        url: https://application-research.github.io/fws-cpi-helm/index.yaml
        return_content: true
      register: helm_repo_response

    - name: Parse Helm repo content
      ansible.builtin.set_fact:
        helm_repo_data: "{{ helm_repo_response.content | from_yaml }}"

    - name: Find the latest available cpi-delta version
      ansible.builtin.set_fact:
        cpi_delta_version: "{{ item.version }}"
      loop: "{{ helm_repo_data.entries['cpi-delta'] }}"
      when: cpi_delta_version is not defined or item.version is version(cpi_delta_version, '>', strict=true)

    - name: Find the latest available cpi-delta-registry version
      ansible.builtin.set_fact:
        cpi_delta_registry_version: "{{ item.version }}"
      loop: "{{ helm_repo_data.entries['cpi-delta-registry'] }}"
      when: cpi_delta_registry_version is not defined or item.version is version(cpi_delta_registry_version, '>', strict=true)

    - name: Find the latest available cpi-edge version
      ansible.builtin.set_fact:
        cpi_edge_version: "{{ item.version }}"
      loop: "{{ helm_repo_data.entries['cpi-edge'] }}"
      when: cpi_edge_version is not defined or item.version is version(cpi_edge_version, '>', strict=true)

    - name: Find the latest available cpi-edge-urid version
      ansible.builtin.set_fact:
        cpi_edge_urid_version: "{{ item.version }}"
      loop: "{{ helm_repo_data.entries['cpi-edge-urid'] }}"
      when: cpi_edge_urid_version is not defined or item.version is version(cpi_edge_urid_version, '>', strict=true)

    - name: Find the latest available cpi-postgresql version
      ansible.builtin.set_fact:
        cpi_postgresql_version: "{{ item.version }}"
      loop: "{{ helm_repo_data.entries['cpi-postgresql'] }}"
      when: cpi_postgresql_version is not defined or item.version is version(cpi_postgresql_version, '>', strict=true)

    - name: Print the versions
      ansible.builtin.debug:
        msg: "cpi-delta: {{ cpi_delta_version }}, cpi-delta-registry: {{ cpi_delta_registry_version }}, cpi-edge: {{ cpi_edge_version }}, cpi-edge-urid: {{ cpi_edge_urid_version }}, cpi-postgresql: {{ cpi_postgresql_version }}"
